### ISSUE TITLE
Paintings and frames are busted

### ISSUE THREAD

**Issue by coldud13** [Skyrat-SS13/Skyrat13#2106] opened 2020-05-22 08:17 UTC
## Round ID:
1422

## Date and Time of Issue:
Server time: 2020-05-22 03:49

## What Map did this Issue occur on:
Box

## Testmerges (If Applicable):
N/A

## Reproduction:
Most likely caused by: https://github.com/Skyrat-SS13/Skyrat13/pull/2080

Buy art crate from cargo, setup canvas on evil and attempt to paint (same result with both crayons and spraycans). The sprite wil change to something different, and not match what you have drawn. Using the frame in hand still allows editing the painting but the sprite is stuck.

My guess is that the sprite changes to the first painting stored in the painting persistance system and changes to that for some reason.

Wall painting frames don't update when a picture is inserted either, didn't test on picture frames though.

## Possible Screenshots of the Issue in question:
![image](https://user-images.githubusercontent.com/6972764/82644752-29766680-9c55-11ea-8f5c-4d2ab0f2da37.png)
Both paintings appear like that, despite not being intentionally drawn like that.
![image](https://user-images.githubusercontent.com/6972764/82644898-65113080-9c55-11ea-9e38-0ce65c9cc14d.png)
Intended paintings.
![image](https://user-images.githubusercontent.com/6972764/82645072-a73a7200-9c55-11ea-81c2-4618e1dbf45d.png)
All other frame sizes share the same problem (each with their own version). Also shows painting frame lack an actual painting despite it being there.

**Comment by jjpark-kb** [comment] 2020-05-22 19:27
Is this even a bug? This is probably due to not wanting to deal with making what is shown on it. Examining it would show it, no?

**Comment by BobJoga** [comment] 2020-05-22 19:30
This is intended behavior. Updating them live would cause too much stress on byond, the paintings only properly update once you finish and name them.

**Comment by jjpark-kb** [comment] 2020-05-22 19:41
As the author of the PR has said it is intended, I will close this.

**Closed by jjpark-kb** 2020-05-22 19:41 UTC

**Comment by coldud13** [comment] 2020-05-24 03:06
> This is intended behavior. Updating them live would cause too much stress on byond, the paintings only properly update once you finish and name them.

These paintings were infact finished and named though. As the title is at the bottom in the window and the finalise button is gone.
